base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('', views.authen, name='authen'),
    path('wel/', views.wel, name='wel'),
    path('upload/', views.upload, name='upload'),
    path('player/<str:play_path>', views.player, name='player'),
    path('download/<str:path>', views.down, name='down'),
    path('<str:wich_type>/home', views.home, name='home'),
    path('goـtoـdirectory/<str:path>/<str:wich_type>', views.go_to_directory, name='go_to_directory'), 
]

blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

#app_name = 'blog'

urlpatterns = [
	path('', views.home, name='home'),
]

web/urls.py
from django.contrib import admin
import os
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('blog/', include('blog.urls')),
]

base/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib import messages

from PIL import Image
from io import BytesIO
from mutagen.mp3 import MP3 as mp3
from mutagen.id3 import ID3
from mutagen.easyid3 import EasyID3

import os
from pathlib import Path
import base64
from io import StringIO




home_dir = settings.BASE_DIR
files_dir = '{}/base/static/base/ser'.format(home_dir)


def player(request, play_path):
	play_path = '/'.join(play_path.split(' > ')[8:])
	return render(request, 'base/player.html', {'path': play_path})

def upload(request):
	fs = FileSystemStorage()
	filename = fs.save(request.FILES['myfile'].name, request.FILES['myfile'])

	return render(request, 'base/wel.html')

def wel(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		if {'username': username, 'password': password} in users:
			messages.add_message(request, messages.INFO, 'login successful')
			return render(request, 'base/wel.html')

		else:
			return redirect('base:authen')
	else:
		return render(request, 'base/wel.html')


def authen(request):
	return render(request, 'base/authen.html')

def files_finder(directory):

	files = []
	musics = []
	video = []
	document = []
	images = []


	def add_file(entry, file_format):

		files.append({'title': entry.name, 'path': entry.path, 'format':file_format})

		if file_format == 'image':
			images.append({'title': entry.name, 'relpath': entry.path, 'path': (' > ').join(entry.path.split('/')), 'format':file_format})

		#adding music's images
		elif file_format == 'mp3':
			try:

				s = ID3(entry.path)
				for i in s:
					if i.startswith("APIC:"):
						img = Image.open(BytesIO(s.get(i).data))
						break

				name = '{}/base/static/base/music_image/'.format(home_dir) + entry.name[:-3] + 'png'
				img.thumbnail((125, 125))
				img.save(name)


				try:
					data = EasyID3(entry.path)
					name = data['title'][0]
					date = data['date'][0]
					artist = data['artist'][0]
					genre = data['genre'][0]
				except:
					name = entry.name[:-4]
					date =''
					artist = ''
					genre = ''

				image_str = entry.name[:-3] + 'png'
				musics.append({'name': name, 'title': entry.name, 'genre': genre, 'artist': artist, 'date': date, 'path': (' > ').join(entry.path.split('/')), 'format':file_format, 'image_str': image_str})



			except:

				try:
					data = EasyID3(entry.path)
					name = data['title'][0]
				except:
					name = entry.name[:-4]

				musics.append({'name': name, 'title': entry.name, 'path': (' > ').join(entry.path.split('/')), 'format':file_format, 'image_str': 'it.png'})



		elif file_format == 'video':
			video.append({'title': entry.name, 'path': (' > ').join(entry.path.split('/')), 'format':file_format})

		elif file_format == 'document':
			document.append({'title': entry.name, 'path': (' > ').join(entry.path.split('/')), 'format':file_format})

	def add_file_from(directory):
		for entry in os.scandir(directory):
			if entry.is_file():
				if entry.path[-3:] in ['mp3', 'm4a', 'mp4', 'MP4']:
					add_file(entry, 'mp3')

				elif entry.path.split('.')[-1] in ['png', 'jpeg', 'JPEG', 'jpg', 'PNG']:
					add_file(entry, 'image')

				elif entry.path[-3:] in ['mp4', 'mkv']:
					add_file(entry, 'video')

				elif entry.path[-3:] in ['pdf', 'out', 'py', 'cpp']:
					add_file(entry, 'document')

				elif entry.is_dir():
					add_file_from(entry.path)

	add_file_from(directory)

	files = sorted(files, key=lambda i: i['title'])
	musics = sorted(musics, key=lambda i: i['name'])
	images = sorted(images, key=lambda i: i['title'])
	video = sorted(video, key=lambda i: i['title'])
	document = sorted(document, key=lambda i: i['title'])

	return files, musics, images, video, document



# ser is for adding files for paths and movies
def ser(directory):

	video = []
	dir_path = []
	files = []
	sub = []
	print(directory)

	def add_file_ser(entry, file_format):

		files.append({'title': entry.name, 'relpath': entry.path, 'path': entry.path, 'format':file_format})

		# adding movies
		if file_format == 'video':
			
			if entry.name[-3:] in ['mp4', 'mkv']:
				video.append({'title': entry.name, 'relpath': entry.path, 'review': True, 'path': (' > ').join(entry.path.split('/')), 'format':file_format})
			else:
				video.append({'title': entry.name, 'relpath': entry.path, 'path': (' > ').join(entry.path.split('/')), 'format':file_format})


		# adding directory path's links
		elif file_format == 'directory':
			dir_path.append({'title': entry.name, 'path': (' > ').join(entry.path.split('/')), 'format':file_format})

		# adding subtitles
		elif file_format == 'sub':
			sub.append({'title': entry.name, 'path': (' > ').join(entry.path.split('/')), 'format':file_format})


	def add_file_from_ser(directory):
		for entry in os.scandir(directory):

			if entry.is_file():
				if entry.path[-3:] in ['mp4', 'mkv']:
					add_file_ser(entry, 'video')

				elif entry.path[-3:] in ['srt', 'pdf']:
					add_file_ser(entry, 'sub')


			elif entry.is_dir():
				print(entry)
				add_file_ser(entry, 'directory')

	add_file_from_ser(directory)


	# sorting all files for better view
	files = sorted(files, key=lambda i: i['title'])
	dir_path = sorted(dir_path, key=lambda i: i['title'])
	video = sorted(video, key=lambda i: i['title'])
	sub = sorted(sub, key=lambda i: i['title'])

	return files, dir_path, video, sub



# this func is for going in to the paths and serv the files on that directory with ser func
def go_to_directory(request, path, wich_type):

	files_dir = ('/').join(path.split(' > '))

	# folder type for viewin title in front & filtering data
	folder_type = wich_type[0].capitalize() + wich_type[1:]

	if wich_type == 'Serials':
		files, dir_path, video, sub = ser(files_dir)
		wich_type = video + dir_path + sub

	context = {
		'files': wich_type,
		'type': folder_type,
	}

	return render(request, 'base/home.html', context)




def home(request, wich_type):
	global files_dir

	# add all type files from directory
	files, musics, images, video, document = files_finder('{}/base/static/base/ed'.format(home_dir))

	# make title start with captal leter for templates
	folder_type = wich_type[0].capitalize() + wich_type[1:]

	# make var for send data to templates
	if wich_type == 'musics':
		wich_type = musics

	elif wich_type == 'files':
		wich_type = files

	elif wich_type == 'images':
		wich_type = images

	elif wich_type == 'video':
		wich_type = video

	elif wich_type == 'document':
		wich_type = document

	elif wich_type == 'serials':
		files, dir_path, video, sub = ser('{}/base/static/base/ser'.format(home_dir))
		wich_type =  dir_path + video


	context = {
		'files': wich_type,
		'type': folder_type,
	}

	return render(request, 'base/home.html', context)


# this func response files for download
def down(request, path):
	print(path)
	global data

	#decode the path
	path = ('/').join(path.split(' > '))
	return FileResponse(open(path, 'rb'), as_attachment=True)


# Create your views here.

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from django.urls import reverse

def home(request):
	return render(request, 'blog/home.html')

# Create your views here.

base/templates/base/authen.html
{% load static %}
<HTML>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    </head>
    <body class="bg-dark">
    	
    	<div class="container-lg">
    		<img class="" style="padding: all;width: auto;position: relative;max-width: 100%;
  text-align: center;" src="{% static 'base/images.png' %}">
	    	<form action="{% url 'base:wel' %}" id="ch" method="post">
	    		{% csrf_token %}
	    		<input type="username" class="form-control" placeholder="Username" name="username">
	    		<br>
	    		<input type="password" class="form-control" placeholder="Password" name="password">
				<br>
	    		<input type="submit" class="btn btn-success" value="Login">

	    	</form>
    	</div>
		
    </body>
</HTML>

base/templates/base/home.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="{% static 'base/bash.png' %}">
	<title>{{ type }}</title>
	<meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!--<link rel="stylesheet" type="text/css" href="{% static 'base/st.css' %}">-->
</head>

<!--<style type="text/css">
	.dropdown-menu .a:focus {background: red; color:#000;}

	.dropdown-menu .dropdown-item {display: inline-block; width: 100%;}

	.dropdown-menu .dropdown-item:active {background: #dc3545;}

	@media only screen and (min-width: 500px) {
		.grid {          
			display: grid;
			justify-content: space-between; 
			grid-template-columns: 33% 33% 33%;
		}
	}
	@media only screen and (max-width: 500px) {
		.grid {
			display: grid;
			justify-content: space-between; 
			grid-template-columns: 100%;
		}
	}

	.grid-container-2 {
		display: grid;
		justify-content: space-between;
		grid-template-columns: 50% 50%;
	}
</style>
-->

<body class="bg-dark">

	<ul class="nav nav-pills nav-fill p-2">
		<li class="nav-item">
			<a href="{% url 'base:wel' %}" class="nav-link"><span class="glyphicon glyphicon-home" ></span>Home</a>
		</li>


		{% if type == 'Musics' %}
			<li class="nav-item">
				<a href="{% url 'base:home' 'musics' %}" class="nav-link active"><span class="glyphicon glyphicon-music" ></span> Music</a>
			</li>
		{% else %}
			<a href="{% url 'base:home' 'musics' %}" class="nav-link"><span class="glyphicon glyphicon-music" ></span> Music</a>

		{% endif %}


		{% if type == 'Images' %}
			<li class="nav-item">
				<a href="{% url 'base:home' 'images' %}" class='nav-link active'><span class="glyphicon glyphicon-picture" ></span> Images</a>
			</li>
		{% else %}
			<li class="nav-item">
				<a href="{% url 'base:home' 'images' %}" class="nav-link"><span class="glyphicon glyphicon-picture" ></span> Images</a>
			</li>
		{% endif %}


		{% if type == 'Document' %}
			<li class="nav-item">
				<a href="{% url 'base:home' 'document' %}" class='nav-link active'><span class="glyphicon glyphicon-file" ></span> Docs</a>
			</li>
		{% else %}
			<li class="nav-item">
				<a href="{% url 'base:home' 'document' %}" class="nav-link"><span class="glyphicon glyphicon-file" ></span> Docs</a>
			</li>
		{% endif %}


		{% if type == 'Serials' %}
			<li class="nav-item">
				<a href="{% url 'base:home' 'serials' %}" class='nav-link active'><span class="glyphicon glyphicon-film" ></span> Movies</a>
			</li>

		{% else %}
			<li class="nav-item">
				<a href="{% url 'base:home' 'serials' %}" class="nav-link"><span class="glyphicon glyphicon-film" ></span> Movies</a>
			</li>
		{% endif %}
	</ul> 


	


	<div class="container-lg">
		<h2 class="text-light">{{ type }}</h2>
		<hr class="text-light">
		{% if files %}
			
			<div class="grid-container">
				{% for i in files %}
						{% if i.format == 'directory' %}
							<div class="file-container crop">
								<div>
									<img src="{{ STATIC_PREFIX }}base/folder.png" width="30" height="30">
									<a style="text-decoration-line: none;" class="text-light" href="{% url 'base:go_to_directory' i.path type %}">{{ i.title }}
									</a>
								</div>
							</div>
						{% endif %}
				{% endfor %}
				<hr class="text-light">
			</div>


			<div class="grid-container-2">
			{% for i in files %}
					{% if i.format == 'video' %}
						<div class="file-container row g-0">
							{% if i.review %}
								
								<a href="{% url 'base:down' i.path %}" style="text-decoration-line: none;" class="text-light">
								<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="white" class="bi bi-play-btn" viewBox="0 0 16 16">
								  <path d="M6.79 5.093A.5.5 0 0 0 6 5.5v5a.5.5 0 0 0 .79.407l3.5-2.5a.5.5 0 0 0 0-.814l-3.5-2.5z"/>
								  <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm15 0a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>
								</svg> {{ i.title|slice:"40" }}</a>
								<hr>
								
							{% else %}
								<a href="{% url 'base:down' i.path %}" style="text-decoration-line: none;" class="text-light">
								<img src="{% static 'base/video.png' %}" width="30" height="30">
								{{ i.title }}</a>
							{% endif %}
							
							
							<hr>
							
						</div>
					{% endif %}
			{% endfor %}
			</div>
			<br>

			<div class="grid-container">
				{% for i in files %}
						{% if i.format == 'sub' %}
							<div class="file-container crop text-light">
								<a href="{% url 'base:down' i.path %}">
								<img src="{% static 'base/pdf.png' %}" width="30" height="30">
								{{ i.title }}</a>
							</div>
						{% endif %}
				{% endfor %}
			</div>

			<div class="grid-container-2">
				{% for i in files %}
						{% if i.format == 'document' %}
							<div class="p-1 m-1">
								<a class="text-light" style="text-decoration-line: none;" href="{% url 'base:down' i.path %}">
								<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-file-earmark-pdf" viewBox="0 0 16 16">
  <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
  <path d="M4.603 14.087a.81.81 0 0 1-.438-.42c-.195-.388-.13-.776.08-1.102.198-.307.526-.568.897-.787a7.68 7.68 0 0 1 1.482-.645 19.697 19.697 0 0 0 1.062-2.227 7.269 7.269 0 0 1-.43-1.295c-.086-.4-.119-.796-.046-1.136.075-.354.274-.672.65-.823.192-.077.4-.12.602-.077a.7.7 0 0 1 .477.365c.088.164.12.356.127.538.007.188-.012.396-.047.614-.084.51-.27 1.134-.52 1.794a10.954 10.954 0 0 0 .98 1.686 5.753 5.753 0 0 1 1.334.05c.364.066.734.195.96.465.12.144.193.32.2.518.007.192-.047.382-.138.563a1.04 1.04 0 0 1-.354.416.856.856 0 0 1-.51.138c-.331-.014-.654-.196-.933-.417a5.712 5.712 0 0 1-.911-.95 11.651 11.651 0 0 0-1.997.406 11.307 11.307 0 0 1-1.02 1.51c-.292.35-.609.656-.927.787a.793.793 0 0 1-.58.029zm1.379-1.901c-.166.076-.32.156-.459.238-.328.194-.541.383-.647.547-.094.145-.096.25-.04.361.01.022.02.036.026.044a.266.266 0 0 0 .035-.012c.137-.056.355-.235.635-.572a8.18 8.18 0 0 0 .45-.606zm1.64-1.33a12.71 12.71 0 0 1 1.01-.193 11.744 11.744 0 0 1-.51-.858 20.801 20.801 0 0 1-.5 1.05zm2.446.45c.15.163.296.3.435.41.24.19.407.253.498.256a.107.107 0 0 0 .07-.015.307.307 0 0 0 .094-.125.436.436 0 0 0 .059-.2.095.095 0 0 0-.026-.063c-.052-.062-.2-.152-.518-.209a3.876 3.876 0 0 0-.612-.053zM8.078 7.8a6.7 6.7 0 0 0 .2-.828c.031-.188.043-.343.038-.465a.613.613 0 0 0-.032-.198.517.517 0 0 0-.145.04c-.087.035-.158.106-.196.283-.04.192-.03.469.046.822.024.111.054.227.09.346z"/>
</svg>
								{{ i.title }}</a>
								
							</div>
						{% endif %}
				{% endfor %}
			</div>

			<div class="m-3 grid">
			{% for i in files %}
					{% if i.format == 'mp3' %}
						<div class="card mb-3 border border-secondary bg-dark" style="max-width: 700px;">
						  <div class="row g-0">
						    <div class="col-md-4">
						    	<a href="{% url 'base:down' i.path %}" style="text-decoration-line: none;">
						      <img src="{{ STATIC_PREFIX }}base/music_image/{{ i.image_str }}" class="img-fluid rounded-start" alt="..."></a>
						    </div>
						    <div class="col-md-8">
						      <div class="card-body">
						        <a href="{% url 'base:down' i.path %}" style="text-decoration-line: none;"><h6 class="card-title text-light">{{ i.name|slice:":20" }}</h6></a><br>
								<audio controls="">
									<source src="{{ STATIC_PREFIX }}base/ed/{{ i.title }}" type="">
								</audio>
						      </div>
						    </div>
						  </div>
						</div>
					{% endif %}

			{% endfor %}
			</div>

			<div class="m-3 grid">
				{% for i in files %}
					{% if i.format == 'image' %}
						<div class="shadow rounded rounded-3 m-2 border border-2 border-secondary">
							<div class="">
								<img src="{{ STATIC_PREFIX }}base/ed/{{ i.title }}" class="card-img-bottom img-fluid  rounded-top" alt="...">

								<div class="p-3">
							    	<p class="card-text text-light">{{ i.title|slice:":30" }}</p>
								</div>
							</div>

							<div class="p-3" >
							  <a href="{% url 'base:down' i.path %}" class="btn btn-primary" style="">Download</a>
							</div>
						</div>
					{% endif %}
				{% endfor %}
			</div>
						
					
			
		{% else %}
			<div class="alert alert-info" role="alert">
			  There is no file!
			</div>
		{% endif %}
	</div>



	<script src="https://vjs.zencdn.net/7.10.2/video.js"></script>
</body>
</html>

base/templates/base/player.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE html>
<html>
<head>
	<title>Online Play</title>
	<meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
	<style type="text/css">
		video {
			width: 100%;
			height: 100%;		}
	</style>


	<video controls>
		<source src="{{ STATIC_PREFIX }}base/ser/{{ path }}">
	</video>

</body>
</html>

base/templates/base/wel.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE html>
<html>
<head>
	<link rel="icon" href="{% static 'base/images.png' %}">
	<title>Home</title>
	<meta charset="UTF-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <!--<link rel="stylesheet" type="text/css" href="{% static 'base/st.css' %}">-->
</head>
<body class="bg-dark">

	
	<ul class="nav nav-pills nav-fill p-2">
		<li class="nav-item">
		<a href="{% url 'base:wel' %}" class="nav-link active"><span class="glyphicon glyphicon-home" ></span> Home</a>
		</li>

		<li class="nav-item">
		<a href="{% url 'base:home' 'musics' %}" class="nav-link"><span class="glyphicon glyphicon-music" ></span> Music</a>
		</li>

		<li class="nav-item">
		<a href="{% url 'base:home' 'images' %}" class="nav-link"><span class="glyphicon glyphicon-picture" ></span> Images</a>
		</li>

		<li class="nav-item">
		<a href="{% url 'base:home' 'document' %}" class="nav-link"><span class="glyphicon glyphicon-file" ></span> Docs</a>
		</li>
		
		<li class="nav-item">
		<a href="{% url 'base:home' 'serials' %}" class="nav-link"><span class="glyphicon glyphicon-film" ></span> Movies</a>
		</li>
	</ul>

	<div class="container-lg">
		<div>
			{% if messages %}
				{% for message in messages %}
					<div class="alert alert-success">{{ message }}</div>
				{% endfor %}
			{% endif %}

			<h2 class="text-light">Home</h2>
			<div class="text-light">
				you can upload you file here and find theme in different categories on left the left menu
			</div>
			<hr class="text-light">
			
			
			<br>
			
			<form action="{% url 'base:upload' %}" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<div>
					<div><input type="file" name="myfile" id="myfile"></div><br>
					<button type="submit" class="btn btn-success" value="Upload">Upload</button>
				</div>
				
			</form>
		</div>
	</div>

	

	<script src="https://vjs.zencdn.net/7.10.2/video.js"></script>
</body>

blog/templates/blog/home.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
</head>
<body>
	<div class="text-container">
		Hello World
		this blog for learning the python & django

		<div class="code-container">
			$ python3 manage.py runserver
		</div>

	</div>
</body>
</html>